version: "3.9"

x-site-base: &php-site
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  working_dir: /var/www/html

services:
  belocalfocussed:
    <<: *php-site
    container_name: belocalfocussed_site
    ports:
      - "8081:80"
    volumes:
      - ./belocalfocussed:/var/www/html

  bizmetron:
    <<: *php-site
    container_name: bizmetron_site
    ports:
      - "8082:80"
    volumes:
      - ./bizmetron:/var/www/html

  golocalpages:
    <<: *php-site
    container_name: golocalpages_site
    ports:
      - "8083:80"
    volumes:
      - ./golocalpages:/var/www/html

  mylocaledge:
    <<: *php-site
    container_name: mylocaledge_site
    ports:
      - "8084:80"
    volumes:
      - ./mylocaledge:/var/www/html

  smartbusinesssearch:
    <<: *php-site
    container_name: smartbusinesssearch_site
    ports:
      - "8085:80"
    volumes:
      - ./smartbusinesssearch:/var/www/html

  uscity:
    <<: *php-site
    container_name: uscity_site
    ports:
      - "8086:80"
    volumes:
      - ./uscity:/var/www/html

  wheretoapp:
    <<: *php-site
    container_name: wheretoapp_site
    ports:
      - "8087:80"
    volumes:
      - ./wheretoapp:/var/www/html
